<?php
/**
 * Focus keywords the theme wrote in earlier versions (2.77.0 to 2.79.1), so that
 * a field still holding one of them is recognised as the theme's own and may be
 * refined. A keyword an editor typed in Rank Math matches none of these.
 *
 * @package Abrahamic
 */

defined( 'ABSPATH' ) || exit;

return array(
	'page:comparisons' => array( 'similarities between judaism christianity and islam', 'similarities between judaism christianity and islam,difference between christianity and islam' ),
	'page:faq' => array( 'abrahamic religions faq,what are the abrahamic religions' ),
	'page:home' => array( 'abrahamic religions,abrahamic faiths' ),
	'page:islamic-dilemma' => array( 'what is the islamic dilemma,islamic dilemma verses' ),
	'page:places' => array( 'abrahamic holy sites' ),
	'page:timeline' => array( 'abrahamic religions timeline' ),
	'post:abrahamic-family-tree' => array( 'abrahamic religions family tree,abrahamic religions venn diagram' ),
	'post:al-ghazali-ibn-rushd-and-the-limits-of-reason' => array( 'al-ghazali and ibn rushd,al-ghazali' ),
	'post:apostasy-in-the-abrahamic-traditions' => array( 'apostasy,apostasy in islam' ),
	'post:deuteronomy-18-18' => array( 'deuteronomy 18:18,prophet like moses' ),
	'post:faith-and-reason-in-medieval-thought' => array( 'faith and reason,medieval philosophy' ),
	'post:food-and-faith' => array( 'kosher and halal,dietary laws' ),
	'post:gog-and-magog-and-the-dajjal' => array( 'gog and magog,dajjal,antichrist' ),
	'post:hagia-sophia' => array( 'hagia sophia history,hagia sophia' ),
	'post:haman-in-the-quran' => array( 'haman in the quran,haman' ),
	'post:harut-and-marut' => array( 'harut and marut,harut marut' ),
	'post:hira-and-quba' => array( 'cave of hira,quba mosque' ),
	'post:how-the-abrahamic-religions-understand-monotheism' => array( 'abrahamic monotheism,monotheistic religions', 'abrahamic monotheism,tawhid,shirk,monotheistic religions' ),
	'post:interfaith-dialogue-in-the-modern-era' => array( 'interfaith dialogue' ),
	'post:interfaith-marriage' => array( 'can a muslim marry a christian,interfaith marriage,muslim marry christian' ),
	'post:is-allah-the-god-of-the-bible' => array( 'is allah and god the same,who is allah in the bible,is allah god' ),
	'post:ishmael-in-the-abrahamic-traditions' => array( 'ishmael in islam,ishmael,is ishmael the father of islam' ),
	'post:islamic-dilemma-reddit' => array( 'islamic dilemma reddit' ),
	'post:jerusalem-in-three-traditions' => array( 'jerusalem,holy city' ),
	'post:jesus-across-the-traditions' => array( 'jesus in islam,isa jesus,who is jesus in islam,jesus', 'jesus in islam,jesus' ),
	'post:jews-under-muslim-rule' => array( 'jews in islam,why do muslims hate jews,jews under muslim rule' ),
	'post:john-the-baptist-in-four-traditions' => array( 'john the baptist,john the baptist in islam,yahya', 'john the baptist,yahya' ),
	'post:judaism-vs-christianity-reddit' => array( 'judaism vs christianity reddit,judaism vs christianity' ),
	'post:mary-across-the-traditions' => array( 'mary in islam,virgin mary' ),
	'post:masbuta-baptism-in-running-water' => array( 'mandaean baptism,masbuta' ),
	'post:millat-ibrahim' => array( 'millat ibrahim,religion of abraham', 'millat ibrahim,religion of abraham,islam and abraham' ),
	'post:muhammad-in-the-bible' => array( 'is muhammad mentioned in the bible,muhammad in the bible,paraclete' ),
	'post:paul-and-peter-two-missions' => array( 'paul and peter,early church' ),
	'post:prayer-across-the-abrahamic-traditions' => array( 'prayer in abrahamic religions,prayer' ),
	'post:religious-law-in-the-abrahamic-traditions' => array( 'religious law,halakhah,sharia' ),
	'post:saul-in-the-quran' => array( 'who is saul in the quran,talut,saul in the quran' ),
	'post:the-amman-message-and-a-common-word' => array( 'a common word,amman message' ),
	'post:the-cairo-genizah' => array( 'cairo genizah' ),
	'post:the-council-of-nicaea' => array( 'council of nicaea,nicene creed', 'council of nicaea,nicene creed,arius' ),
	'post:the-five-great-sees' => array( 'pentarchy,five great sees' ),
	'post:the-gospel-of-barnabas' => array( 'gospel of barnabas,the gospel of barnabas' ),
	'post:the-islamic-dilemma' => array( 'islamic dilemma,surah 5:46', 'islamic dilemma,surah 5:46,what does the quran say about the bible' ),
	'post:the-kaaba' => array( 'who built the kaaba,kaaba history,mecca and kaaba' ),
	'post:the-king-and-the-pharaoh' => array( 'joseph king of egypt,pharaoh' ),
	'post:the-messiah-in-three-traditions' => array( 'messiah meaning,what does messiah mean,messiah in islam,al masih' ),
	'post:the-parting-of-the-ways' => array( 'parting of the ways,judaism and christianity' ),
	'post:the-population-of-the-abrahamic-religions' => array( 'abrahamic religions population,largest religion in the world' ),
	'post:the-preservation-and-transmission-of-scripture' => array( 'preservation of scripture,quran preservation' ),
	'post:the-sabians-in-classical-muslim-scholarship' => array( 'sabians of harran,sabians' ),
	'post:the-sabians-of-the-quran' => array( 'sabians in the quran,sabians' ),
	'post:the-stations-of-the-hajj' => array( 'stations of hajj,hajj', 'stations of hajj,hajj,mecca and kaaba' ),
	'post:the-symbols-of-the-four-traditions' => array( 'abrahamic religions symbols,star of david' ),
	'post:understanding-the-bible-and-the-quran-in-historical-context' => array( 'bible and quran,historical context' ),
	'post:war-and-peace-in-the-abrahamic-traditions' => array( 'are abrahamic religions violent,is islam a religion of peace,religious violence', 'are abrahamic religions violent,religious violence' ),
	'post:what-archaeology-tells-us-about-the-ancient-near-east' => array( 'ancient near east archaeology,archaeology' ),
	'post:what-does-begotten-mean' => array( 'begotten meaning,what does begotten mean in the bible,only begotten son' ),
	'post:what-language-did-abraham-speak' => array( 'what language did abraham speak' ),
	'post:what-the-quran-says-about-the-bible' => array( 'what does the quran say about the bible,injil,zabur,torah in islam' ),
	'post:where-was-abraham-from' => array( 'where was abraham from,ur of the chaldees' ),
	'post:who-was-abraham' => array( 'who was abraham,abraham', 'who was abraham,abraham in islam,abraham' ),
	'post:who-was-kedar' => array( 'kedar,kedar in the bible' ),
);
