<?php
/**
 * Rank Math focus keywords (primary first), chosen so that every article and
 * page meets Rank Math's content tests: the primary keyword appears in the
 * address, the search title (at its start), the description, the opening, a
 * subheading and the featured image's alt text, and all keywords together give
 * a density between 1% and 2.5%. Generated from the Rank Math audit (2.80.0).
 *
 * @package Abrahamic
 */

defined( 'ABSPATH' ) || exit;

return array(
	'page:home' => 'abrahamic faiths,abrahamic religions',
	'page:articles' => 'journal',
	'page:judaism' => 'judaism',
	'page:christianity' => 'christianity',
	'page:islam' => 'islam,muslims',
	'page:sacred-texts' => 'sacred texts,scripture',
	'page:figures' => 'figures,prophet',
	'page:places' => 'places,abrahamic holy sites,sacred',
	'page:glossary' => 'glossary,hebrew',
	'page:comparisons' => 'comparisons,similarities between judaism christianity and islam,difference between christianity and islam,traditions,compare',
	'page:islamic-dilemma' => 'islamic dilemma,islamic dilemma verses',
	'page:guides' => 'religions',
	'page:research' => 'research',
	'page:about' => 'about,site',
	'page:editorial-policy' => 'editorial policy,sources',
	'page:contact' => 'contact',
	'page:privacy-policy' => 'privacy policy,privacy',
	'page:terms' => 'terms',
	'page:knowledge-base' => 'reference',
	'page:timeline' => 'timeline,abrahamic religions timeline,century,centuries',
	'page:faq' => 'faq,abrahamic religions faq,what are the abrahamic religions,abrahamic religions',
	'page:topics' => 'topics',
	'page:site-map' => 'sitemap',
	'page:donate' => 'donate',
	'page:dmca' => 'dmca,licence',
	'page:thank-you' => 'thank you',
	'page:tanakh' => 'tanakh',
	'page:bible' => 'bible',
	'page:quran' => 'qur’an,surah',
	'page:mandaeism' => 'mandaeism,mandaean',
	'post:who-was-abraham' => 'who was abraham,abraham in islam,father',
	'post:how-the-abrahamic-religions-understand-monotheism' => 'monotheism,tawhid,shirk,monotheistic religions',
	'post:understanding-the-bible-and-the-quran-in-historical-context' => 'historical context,historical,bible and the qur’an',
	'post:jerusalem-in-three-traditions' => 'jerusalem,holy city',
	'post:prayer-across-the-abrahamic-traditions' => 'abrahamic traditions,worship',
	'post:what-archaeology-tells-us-about-the-ancient-near-east' => 'archaeology',
	'post:faith-and-reason-in-medieval-thought' => 'faith and reason,medieval philosophy,reason',
	'post:interfaith-dialogue-in-the-modern-era' => 'interfaith dialogue,dialogue',
	'post:millat-ibrahim' => 'millat ibrahim,path of abraham,monotheism,hanif',
	'post:who-was-kedar' => 'who was kedar,kedar in the bible,arabs',
	'post:john-the-baptist-in-four-traditions' => 'john the baptist,john the baptist in islam,yahya',
	'post:masbuta-baptism-in-running-water' => 'baptism',
	'post:the-sabians-of-the-quran' => 'sabians',
	'post:the-king-and-the-pharaoh' => 'king and the pharaoh,pharaoh',
	'post:jesus-across-the-traditions' => 'jesus,isa jesus,who is jesus in islam',
	'post:mary-across-the-traditions' => 'mary,virgin mary',
	'post:the-preservation-and-transmission-of-scripture' => 'transmission,quran preservation,scripture',
	'post:al-ghazali-ibn-rushd-and-the-limits-of-reason' => 'ibn rushd',
	'post:the-amman-message-and-a-common-word' => 'amman message',
	'post:the-cairo-genizah' => 'cairo genizah,jewish',
	'post:haman-in-the-quran' => 'haman',
	'post:the-population-of-the-abrahamic-religions' => 'population,largest religion in the world',
	'post:paul-and-peter-two-missions' => 'paul and peter,early church,peter',
	'post:apostasy-in-the-abrahamic-traditions' => 'apostasy,apostasy in islam',
	'post:the-sabians-in-classical-muslim-scholarship' => 'classical muslim,sabians',
	'post:abrahamic-family-tree' => 'family tree,abrahamic religions venn diagram,family,diagram',
	'post:the-council-of-nicaea' => 'council of nicaea,nicene creed,arius,council',
	'post:the-five-great-sees' => 'great sees,five great sees,patriarch',
	'post:hagia-sophia' => 'hagia sophia',
	'post:the-stations-of-the-hajj' => 'hajj,mecca and kaaba',
	'post:hira-and-quba' => 'hira,quba mosque',
	'post:what-language-did-abraham-speak' => 'what language did abraham speak,abraham',
	'post:the-parting-of-the-ways' => 'parting of the ways,judaism and christianity,jews,synagogue',
	'post:where-was-abraham-from' => 'where was abraham from,ur of the chaldees,harran',
	'post:the-symbols-of-the-four-traditions' => 'symbols,star of david',
	'post:religious-law-in-the-abrahamic-traditions' => 'religious law,halakhah,sharia,canon law',
	'post:food-and-faith' => 'food and faith,meat,halal,kosher,dietary laws',
	'post:war-and-peace-in-the-abrahamic-traditions' => 'war and peace,is islam a religion of peace,religious violence,peace',
	'post:the-islamic-dilemma' => 'islamic dilemma,surah 5:46,what does the quran say about the bible,dilemma',
	'post:islamic-dilemma-reddit' => 'islamic dilemma reddit,islamic dilemma',
	'post:judaism-vs-christianity-reddit' => 'judaism vs christianity,judaism vs christianity reddit,judaism',
	'post:the-messiah-in-three-traditions' => 'messiah,what does messiah mean,messiah in islam,al masih',
	'post:ishmael-in-the-abrahamic-traditions' => 'ishmael,is ishmael the father of islam',
	'post:is-allah-the-god-of-the-bible' => 'allah,who is allah in the bible,is allah god',
	'post:the-gospel-of-barnabas' => 'gospel of barnabas,the gospel of barnabas',
	'post:what-the-quran-says-about-the-bible' => 'what the qur’an says,injil,zabur',
	'post:the-kaaba' => 'kaaba,kaaba history,mecca and kaaba',
	'post:saul-in-the-quran' => 'saul,talut,saul in the quran',
	'post:interfaith-marriage' => 'interfaith marriage,muslim marry christian,marriage',
	'post:gog-and-magog-and-the-dajjal' => 'gog and magog,dajjal',
	'post:what-does-begotten-mean' => 'begotten,what does begotten mean in the bible,only begotten son',
	'post:harut-and-marut' => 'harut and marut,harut marut',
	'post:deuteronomy-18-18' => 'deuteronomy 18,prophet like moses,like',
	'post:muhammad-in-the-bible' => 'muhammad in the bible,paraclete,muhammad',
	'post:jews-under-muslim-rule' => 'jews under muslim rule,why do muslims hate jews,under',
	'post:galilee' => 'galilee,capernaum',
	'post:safed-and-tiberias' => 'safed and tiberias,safed',
	'post:shiloh-and-masada' => 'shiloh and masada,masada',
	'post:patmos-and-mount-athos' => 'patmos and mount athos,mount athos',
	'post:christian-pilgrimage' => 'christian pilgrimage,santiago de compostela',
	'post:masjid-al-aqsa' => 'masjid al-aqsa,al-aqsa,night journey',
	'post:badr-and-uhud' => 'badr and uhud',
	'post:kairouan' => 'kairouan',
	'post:tigris-and-euphrates' => 'tigris and euphrates,tigris',
);
