<?php
/**
 * Short search titles: with " | Abrahamic Religions" every title stays under
 * 60 characters, and each begins with its Rank Math focus keyword. Keyed by
 * starter-content key; the headline on the page is unchanged. A post's own
 * "Search title" (_abr_seo_title) takes precedence.
 *
 * @package Abrahamic
 */

defined( 'ABSPATH' ) || exit;

return array(
	'page:home' => 'Abrahamic faiths: a clear guide',
	'page:articles' => 'Journal: essays on faith',
	'page:judaism' => 'Judaism: faith, history and practice',
	'page:christianity' => 'Christianity: history and beliefs',
	'page:islam' => 'Islam: history, beliefs and practice',
	'page:sacred-texts' => 'Sacred texts of the Abrahamic faiths',
	'page:figures' => 'Figures of the Abrahamic religions',
	'page:places' => 'Places: the holy sites of four faiths',
	'page:glossary' => 'Glossary: clear terms of four faiths',
	'page:comparisons' => 'Comparisons of the four faiths',
	'page:islamic-dilemma' => 'Islamic Dilemma: 5 clear verses',
	'page:guides' => 'Religions: a clear guide to the four',
	'page:research' => 'Research: a clear guide to sources',
	'page:about' => 'About: a free guide to four faiths',
	'page:editorial-policy' => 'Editorial policy: honest, sourced',
	'page:contact' => 'Contact: helpful answers to questions',
	'page:privacy-policy' => 'Privacy policy: clear and honest',
	'page:terms' => 'Terms of use: clear and fair',
	'page:knowledge-base' => 'Reference: clear guides to the faiths',
	'page:timeline' => 'Timeline of the Abrahamic religions',
	'page:faq' => 'FAQ: the Abrahamic religions',
	'page:topics' => 'Topics: a clear way to browse',
	'page:site-map' => 'Sitemap: a clear list of every page',
	'page:donate' => 'Donate: keep this free guide alive',
	'page:dmca' => 'DMCA and copyright notices',
	'page:thank-you' => 'Thank you: your gift keeps it free',
	'page:tanakh' => 'Tanakh: a treasure, the Hebrew Bible',
	'page:bible' => 'Bible: a clear guide to its 3 canons',
	'page:quran' => 'Qur’an: the 114 surahs, a clear guide',
	'page:mandaeism' => 'Mandaeism: the baptismal faith',
	'post:who-was-abraham' => 'Who was Abraham? Father of nations',
	'post:how-the-abrahamic-religions-understand-monotheism' => 'Monotheism: 4 paths of faith in God',
	'post:understanding-the-bible-and-the-quran-in-historical-context' => 'Historical context: 2 great books',
	'post:jerusalem-in-three-traditions' => 'Jerusalem in faith and history',
	'post:prayer-across-the-abrahamic-traditions' => 'Abrahamic traditions: faith in prayer',
	'post:what-archaeology-tells-us-about-the-ancient-near-east' => 'Archaeology: 3 great inscriptions',
	'post:faith-and-reason-in-medieval-thought' => 'Faith and reason in medieval thought',
	'post:interfaith-dialogue-in-the-modern-era' => 'Interfaith dialogue since 1965: hope',
	'post:millat-ibrahim' => 'Millat Ibrahim: Abraham’s pure faith',
	'post:who-was-kedar' => 'Who was Kedar? Arabs and prophets',
	'post:john-the-baptist-in-four-traditions' => 'John the Baptist in four traditions',
	'post:masbuta-baptism-in-running-water' => 'Baptism in running water: masbuta',
	'post:the-sabians-of-the-quran' => 'Sabians of the Qur’an',
	'post:the-king-and-the-pharaoh' => 'King and the Pharaoh: a clear answer',
	'post:jesus-across-the-traditions' => 'Jesus: a clear guide across 4 faiths',
	'post:mary-across-the-traditions' => 'Mary: a beloved figure of faith',
	'post:the-preservation-and-transmission-of-scripture' => 'Transmission of scripture: clear view',
	'post:al-ghazali-ibn-rushd-and-the-limits-of-reason' => 'Ibn Rushd: faith and reason in 1180',
	'post:the-amman-message-and-a-common-word' => 'Amman Message of 2004: a hopeful word',
	'post:the-cairo-genizah' => 'Cairo Genizah: a Jewish treasure',
	'post:haman-in-the-quran' => 'Haman in the Qur’an',
	'post:the-population-of-the-abrahamic-religions' => 'Population of the Abrahamic religions',
	'post:paul-and-peter-two-missions' => 'Paul and Peter: two missions',
	'post:apostasy-in-the-abrahamic-traditions' => 'Apostasy in the Abrahamic traditions',
	'post:the-sabians-in-classical-muslim-scholarship' => 'Classical Muslim views of the Sabians',
	'post:abrahamic-family-tree' => 'Family tree of faith: 4 traditions',
	'post:the-council-of-nicaea' => 'Council of Nicaea, 325',
	'post:the-five-great-sees' => 'Great sees: the five of the church',
	'post:hagia-sophia' => 'Hagia Sophia: church, mosque, museum',
	'post:the-stations-of-the-hajj' => 'Hajj: the stations of the pilgrimage',
	'post:hira-and-quba' => 'Hira and Quba: where faith began, 610',
	'post:what-language-did-abraham-speak' => 'What language did Abraham speak?',
	'post:the-parting-of-the-ways' => 'Parting of the ways: church and Jews',
	'post:where-was-abraham-from' => 'Where was Abraham from?',
	'post:the-symbols-of-the-four-traditions' => 'Symbols of faith: the 4 traditions',
	'post:religious-law-in-the-abrahamic-traditions' => 'Religious law: halakhah and sharia',
	'post:food-and-faith' => 'Food and faith: kosher and halal',
	'post:war-and-peace-in-the-abrahamic-traditions' => 'War and peace in the Abrahamic faiths',
	'post:the-islamic-dilemma' => 'Islamic Dilemma: the answer',
	'post:islamic-dilemma-reddit' => 'Islamic Dilemma Reddit Q&A',
	'post:judaism-vs-christianity-reddit' => 'Judaism vs Christianity: clear Q&A',
	'post:the-messiah-in-three-traditions' => 'Messiah: the anointed one of faith',
	'post:ishmael-in-the-abrahamic-traditions' => 'Ishmael: the devoted son of Abraham',
	'post:is-allah-the-god-of-the-bible' => 'Allah and the Bible: a clear answer',
	'post:the-gospel-of-barnabas' => 'Gospel of Barnabas: an honest look',
	'post:what-the-quran-says-about-the-bible' => 'What the Qur’an says of 3 great books',
	'post:the-kaaba' => 'Kaaba: history of a house of faith',
	'post:saul-in-the-quran' => 'Saul in the Qur’an: Talut’s faith',
	'post:interfaith-marriage' => 'Interfaith marriage: a clear guide',
	'post:gog-and-magog-and-the-dajjal' => 'Gog and Magog, the Dajjal and hope',
	'post:what-does-begotten-mean' => 'Begotten: a clear look at John 3:16',
	'post:harut-and-marut' => 'Harut and Marut: a clear account',
	'post:deuteronomy-18-18' => 'Deuteronomy 18:18: a clear prophecy',
	'post:muhammad-in-the-bible' => 'Muhammad in the Bible: clear passages',
	'post:jews-under-muslim-rule' => 'Jews under Muslim rule: honest record',
	'post:galilee' => 'Galilee: 4 great sites of Jesus',
	'post:safed-and-tiberias' => 'Safed and Tiberias: 2 great cities',
	'post:shiloh-and-masada' => 'Shiloh and Masada: 2 great sites',
	'post:patmos-and-mount-athos' => 'Patmos and Mount Athos: 2 great sites',
	'post:christian-pilgrimage' => 'Christian pilgrimage: 3 great shrines',
	'post:masjid-al-aqsa' => 'Masjid al-Aqsa: 1 of 3 great mosques',
	'post:badr-and-uhud' => 'Badr and Uhud: 2 great battles',
	'post:kairouan' => 'Kairouan: great holy city since 670',
	'post:tigris-and-euphrates' => 'Tigris and Euphrates: 2 great rivers',
);
